//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.13 at 05:32:26 PM IST 
//


package com.trabeya.core_bank.accounts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="own_source_user_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="own_source_account_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="own_destination_account_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transfer_amount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ownSourceUserId",
    "ownSourceAccountNo",
    "ownDestinationAccountNo",
    "transferAmount"
})
@XmlRootElement(name = "ownFundTransfer")
public class OwnFundTransfer {

    @XmlElement(name = "own_source_user_id", required = true)
    protected String ownSourceUserId;
    @XmlElement(name = "own_source_account_no", required = true)
    protected String ownSourceAccountNo;
    @XmlElement(name = "own_destination_account_no", required = true)
    protected String ownDestinationAccountNo;
    @XmlElement(name = "transfer_amount")
    protected double transferAmount;

    /**
     * Gets the value of the ownSourceUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnSourceUserId() {
        return ownSourceUserId;
    }

    /**
     * Sets the value of the ownSourceUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnSourceUserId(String value) {
        this.ownSourceUserId = value;
    }

    /**
     * Gets the value of the ownSourceAccountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnSourceAccountNo() {
        return ownSourceAccountNo;
    }

    /**
     * Sets the value of the ownSourceAccountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnSourceAccountNo(String value) {
        this.ownSourceAccountNo = value;
    }

    /**
     * Gets the value of the ownDestinationAccountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnDestinationAccountNo() {
        return ownDestinationAccountNo;
    }

    /**
     * Sets the value of the ownDestinationAccountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnDestinationAccountNo(String value) {
        this.ownDestinationAccountNo = value;
    }

    /**
     * Gets the value of the transferAmount property.
     * 
     */
    public double getTransferAmount() {
        return transferAmount;
    }

    /**
     * Sets the value of the transferAmount property.
     * 
     */
    public void setTransferAmount(double value) {
        this.transferAmount = value;
    }

}
